---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/lottery?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: qwe007
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/lottery?serverTimezone=UTC&characterEncoding=UTF-8
    username: lottery
    password: Lott$321
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

---
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8