name: lottery-ci

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2.3.4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: |
        ./gradlew --version
        ./gradlew build
        
    - name: Upload S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_KEY }}
      run: |
        aws s3 cp \
          --region ap-northeast-2 \
          ./build/libs/ s3://lottery-ci --exclude "*" --include "*.jar"

