name: lottery-ci

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      uses: actions/checkout@v2.3.4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'gradle'

    - name: Build with Gradle
      run: gradle build
      
    - name: Upload S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_KEY }}
      run: |
        aws s3 cp \
          --region ap-northeast-2 \
          ./build/libs/*.jar s3://lottery-ci
